---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-aircast"
  ADDON_SLUG: "aircast"
  ADDON_TARGET: "aircast"

  ADDON_ARMV7: "false"
  ADDON_LEGACY_TAGS: "true"

  ADDON_AARCH64_BASE: "hassioaddons/ubuntu-base-aarch64:2.3.1"
  ADDON_AMD64_BASE: "hassioaddons/ubuntu-base-amd64:2.3.1"
  ADDON_ARMHF_BASE: "hassioaddons/ubuntu-base-armhf:2.3.1"
  ADDON_I386_BASE: "hassioaddons/ubuntu-base-i386:2.3.1"
